// components/profile.vue
<template>
  <div class="profile">
    <header :class="{
      'with-banner': !!profile.banner,
    }">
      <div v-if="profile.banner" class="banner" :style="{
        background: profile.banner
          ? `url(${profile.banner}) no-repeat center center`
          : `#667`,
        backgroundSize: profile.banner ? 'cover' : undefined,
      }" />
      <div class="content">
        <NostringSpace>
          <div class="avatar-wrapper">
            <Avatar :image-url="profile.avatar" />
          </div>
          <div class="actions">
            <NostringButton>Chat</NostringButton>
            <NostringButton>Follow</NostringButton>
          </div>
        </NostringSpace>
        <NameDisplay header>{{
          profile.displayName || profile.username || profile.pubkey.substr(0, 12)
        }}</NameDisplay>
        <Name :value="profile.username || profile.pubkey.substr(0, 12)" />
      </div>
    </header>
    <div>{{ profile.bio }}</div>
    <div>0 Following 0 Follower</div>
  </div>
</template>

<script setup lang="ts">
interface Props {
  mini?: boolean;
  profile: Object;
}

const props = withDefaults(defineProps<Props>(), {
  mini: false,
});
</script>

<style lang="scss">
.profile {
  display: flex;
  flex-direction: column;
  gap: 5px;

  header {
    padding-top: 78px;
    /* 128/2+10 */

    .banner {
      height: 196px;
    }

    .content {
      padding: 10px;
      display: flex;
      flex-direction: column;

      .avatar-wrapper {
        position: relative;
        width: 21.33%;
        max-width: 138px;
        /* 128+5x2 */
        max-height: 138px;
        padding-bottom: 21.33%;

        .avatar {
          position: absolute;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
        }

        margin-top: -10.665%;
        /* 21.33/2 */
      }

      .actions {
        flex-grow: 1;
        display: flex;
        flex-direction: row;
        align-items: flex-start;
        justify-content: flex-end;
        gap: 10px;
      }
    }

    &.with-banner {
      padding: 0;
    }
  }
}
</style>

// src/routes/Profile.svelte
<script lang="ts">
    import Space from "$lib/ui/Space.svelte";
    import NIP05 from "./NIP05.svelte";
    import NIP19 from "./NIP19.svelte";

    import ProfileName from "./ProfileName.svelte";

    export let profile: any;
    export let mini: boolean = false;
</script>

<div class="profile">
    <header>
        <div class="banner" />
        <div class="content">
            <Space>
                <div class="avatar-wrapper" />
                <div class="actions" />
            </Space>
            <Space>
                <ProfileName {profile} />
                <NIP05 {profile} />
            </Space>
            <div class="nip19-wrapper">
                <NIP19 nip19={profile.nip19} />
            </div>
        </div>
    </header>
    <div class="bio">blabla</div>
    <div class="meta">blabla</div>
    <div class="stat">blabla</div>
</div>

<style lang="scss">
    .profile {
        display: flex;
        flex-direction: column;
        gap: 5px;

        header {
            padding-top: 88px;

            &.with-banner {
                padding: 0;
            }

            .banner {
                height: 196px;
            }

            .content {
                padding: 10px;
                display: flex;
                flex-direction: column;

                .avatar-wrapper {
                    --width: calc(min(max(21.33%, 74px), 138px));
                    position: relative;
                    width: var(--width);
                    padding-bottom: var(--width);
                    margin-top: calc(37px - var(--width));
                    flex-shrink: 0;

                    .avatar {
                        position: absolute;
                        top: 0;
                        right: 0;
                        bottom: 0;
                        left: 0;
                    }
                }

                .actions {
                    flex-grow: 1;
                    display: flex;
                    flex-direction: row;
                    align-items: flex-start;
                    justify-content: flex-end;
                    gap: 10px;
                }
            }
        }

        .bio {
            padding-left: 10px;
            padding-right: 10px;
        }

        .meta {
            padding-left: 3px;
            padding-right: 3px;
        }

        .stat {
            padding: 5px 10px;
        }
    }
</style>
