// components/nostring/form/index.vue
<template>
    <form class="ns-form" @submit="handleSubmit">
        <slot />
    </form>
</template>

<script setup lang="ts">
const handleSubmit = (e:any)=>{
    e.preventDefault();
    return false;
}
</script>

<style lang="scss">
.ns-form {
    display: flex;
    flex-flow: column;
    gap: 10px;
}
</style>

// src/lib/ui/Form.svelte
<script lang="ts">
    const handleSubmit = (e: any) => {
        e.preventDefault();
        return false;
    };
</script>

<form class="ns-form" on:submit={handleSubmit}>
    <slot />
</form>

<style lang="scss">
    .ns-form {
        display: flex;
        flex-flow: column;
        gap: 10px;
    }
</style>
