// src/lib/ui/Input.svelte
<script setup lang="ts">
    import { createEventDispatcher } from "svelte";

    export let value: string;
    export let tag: "input" | "textarea" = "input";

    const dispath = createEventDispatcher();

    function onClick(event: any) {
        dispath("click", event);
    }

    const handleChange = (v: string) => {
        dispath("update:value", v);
    };
</script>

<template />

<svelte:element this={tag} bind:value on:change={handleChange} />

// components/nostring/input.vue
<template>
    <component :is="tag" v-model:value="props.value" @change="handleChange" />
</template>

<script setup lang="ts">
interface Props {
  value?: string;
}

const props = withDefaults(defineProps<Props>(), {
});

const emit = defineEmits(['upadte:value']);
const tag = ref('input');

const handleChange = (v:string)=>{
    emit('update:value', v);
}
</script>
